apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kneutral-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kneutral-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "kneutral-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kneutral-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kneutral-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect={{ .Values.operator.leaderElection.enabled }}
        - --metrics-bind-address=:{{ .Values.metrics.port }}
        - --health-probe-bind-address=:{{ .Values.healthProbe.port }}
        - --api-bind-address=:{{ .Values.api.port }}
        {{- if .Values.operator.watchNamespace }}
        - --namespace={{ .Values.operator.watchNamespace }}
        {{- end }}
        - --zap-log-level={{ .Values.operator.logLevel }}
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Values.operator.watchNamespace | quote }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        - name: health
          containerPort: {{ .Values.healthProbe.port }}
          protocol: TCP
        - name: api
          containerPort: {{ .Values.api.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}