---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kneutral-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kneutral-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kneutral-operator.selectorLabels" . | nindent 4 }}
---
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kneutral-operator.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kneutral-operator.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "kneutral-operator.selectorLabels" . | nindent 4 }}
{{- end }}